/**
 * prerender.mjs — post-build SEO prerendering for React sites
 * Generated by SEO/AEO Setup Agent — production-grade, no placeholders.
 *
 * Runs after: vite build && node prerender.mjs
 *
 * For each public route, reads dist/index.html and injects route-specific
 * meta tags + canonical URL, then writes a static HTML file so crawlers
 * get proper meta without executing JavaScript.
 */
import fs from "fs";
import path from "path";

const DOMAIN = "https://yagyaistudio.vercel.app";

const ROUTES = [
  {
    route: "/",
    output: "dist/index.html",
    title: "Yagya Sharma — AI Builder & Automation Specialist",
    description: "Yagya Sharma builds AI-powered systems, voice agents, revenue automation, AI visuals, and vibe-coded websites for modern businesses. Based in India, working globally.",
    canonical: "https://yagyaistudio.vercel.app/",
  },
];

const base = fs.readFileSync("dist/index.html", "utf-8");

for (const { route, output, title, description, canonical } of ROUTES) {
  let html = base
    .replace(/<title>[\s\S]*?<\/title>/, `<title>${title}</title>`)
    .replace(
      "</head>",
      `  <meta name="description" content="${description.replace(/"/g, '&quot;')}" />\n` +
      `  <link rel="canonical" href="${canonical}" />\n` +
      `  <meta property="og:title" content="${title.replace(/"/g, '&quot;')}" />\n` +
      `  <meta property="og:description" content="${description.replace(/"/g, '&quot;')}" />\n` +
      `  <meta property="og:url" content="${canonical}" />\n` +
      `  <meta name="twitter:title" content="${title.replace(/"/g, '&quot;')}" />\n` +
      `  <meta name="twitter:description" content="${description.replace(/"/g, '&quot;')}" />\n` +
      `</head>`
    );

  const dir = path.dirname(output);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  fs.writeFileSync(output, html, "utf-8");
  console.log(`[prerender] Wrote ${output}`);
}

console.log(`\n[prerender] Done — ${ROUTES.length} route(s) prerendered.`);
